owner: rizkyhaksono
repo: uptime

sites:
  - name: Portfolio
    url: https://natee.me
    icon: https://natee.me/favicon.ico
  - name: Portfolio API v3
    url: https://api.natee.me/swagger
  - name: Smart Recycling Frontend
    url: https://smartrecycling.natee.me
  - name: Smart Recycling Backend
    url: https://api-smartrecycling.natee.me
  - name: Otakudesu Backend
    url: https://otakudesu.natee.me/api
    icon: https://api.otakudesu.natee.my.id/favicon.ico
  - name: Otakudesu Frontend
    url: https://otakudesu.natee.my.id
    icon: https://otakudesu.natee.my.id/favicon.ico
  - name: Otakudesu Docs
    url: https://otakudesudocs.natee.my.id
    icon: https://otakudesudocs.natee.my.id/favicon.ico
  - name: Apel Manis
    url: https://apelmanis.natee.my.id
    icon: https://apelmanis.natee.my.id/favicon.ico
  - name: Info Gempa
    url: https://gempa.natee.me/
  - name: NestJS Inventory API
    url: https://inventory.natee.me/api
  - name: Mahati Admin
    url: https://mahati.natee.me
  - name: Mahati API
    url: https://mahati.xyzuan.my.id
  - name: Jenkins Natee
    url: https://jenkins.natee.me
  - name: Nginx Natee
    url: https://nginx.natee.me
  - name: Portainer Natee
    url: https://portainer.natee.me

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.natee.my.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime RH
  theme: dark
  introTitle: "**Upptime** is the uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: This page is hosted on GitHub [rizkyhaksono/uptime]($REPO) project since @2024-02-02, & created by [rizkyhaksono](https://rizkyhaksono.natee.my.id/).

workflowSchedule:
graphs: "0 */6 * * *"
responseTime: "10 */6 * * *"
staticSite: "20 */6 * * *"
summary: "30 */6 * * *"
updateTemplate: "0 0 * * *"
updates: "40 */6 * * *"
uptime: "*/5 * * * *"
