owner: rizkyhaksono
repo: uptime

sites:
  - name: Uptime Monitor v2
    url: https://stats.uptimerobot.com/RlWv1DOX9w
    icon: https://stats.uptimerobot.com/assets/favicon.ico
  - name: Uptime Monitor v3
    url: https://status.nateee.com/status/all
  - name: Portfolio (.my.id)
    url: https://natee.my.id
    icon: https://natee.my.id/favicon.ico
  - name: Portfolio (.com)
    url: https://nateee.com
    icon: https://natee.com/favicon.ico
  - name: Portfolio (.io)
    url: https://nateon.io
    icon: https://nateon.io/favicon.ico
  - name: Portfolio API v3
    url: https://api.natee.my.id/docs
  - name: Nateeflix API
    url: https://api.flix.natee.my.id/swagger
  - name: Nateegami API
    url: https://api.gami.natee.my.id/swagger
  - name: Otakudesu API
    url: https://api.otakudesu.natee.my.id/api
    icon: https://api.otakudesu.natee.my.id/favicon.ico
  - name: Otakudesu Frontend
    url: https://otakudesu.natee.my.id
    icon: https://otakudesu.natee.my.id/favicon.ico
  - name: Otakudesu Docs
    url: https://otakudesudocs.natee.my.id
    icon: https://otakudesudocs.natee.my.id/favicon.ico
  - name: Apel Manis
    url: https://apelmanis.natee.my.id
    icon: https://apelmanis.natee.my.id/favicon.ico
  - name: Info Gempa
    url: https://gempa.natee.my.id
  - name: NestJS Inventory API
    url: https://inventory.natee.my.id/api
  - name: NestJS Book API
    url: https://api.book.natee.my.id/api
  - name: Mahati Admin
    url: https://mahati.natee.my.id
  - name: Mahati API
    url: https://mahati.xyzuan.my.id
  - name: Jenkins Natee
    url: https://jenkins.natee.my.id/login?from=%2F
  - name: Nginx Natee
    url: https://nginx.natee.my.id
  - name: Portainer Natee
    url: https://portainer.natee.my.id
  - name: Short Link BE
    url: https://api.link.natee.my.id/docs/api
  - name: Short Link FE
    url: https://shortlink.natee.my.id
  - name: Natee RabbitMQ
    url: https://rabbitmq.natee.my.id
    icon: https://rabbitmq.natee.my.id/favicon.ico
  - name: NyanDrive Docs
    url: https://docs.nyandrive.com
    icon: https://docs.nyandrive.com/img/favicon.ico
  - name: serahweb (natee)
    url: https://serahweb.nateee.com
    icon: https://serahweb.nateee.com/favicon.ico
  - name: serahweb (serah)
    url: https://serahweb.com
    icon: https://serahweb.com/favicon.ico
  - name: Natee Tracker
    url: https://tracker.nateon.io
    icon: https://tracker.nateon.io/favicon.svg

status-website:
  cname: uptime.natee.my.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime RH
  theme: dark
  introTitle: "This is my uptime status page. See the status of my sites and services."
  introMessage: "All systems operational. If you have any questions, please contact me."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: This page is hosted on GitHub [rizkyhaksono/uptime]($REPO) project since @2024-02-02, & created by [rizkyhaksono](https://rizkyhaksono.natee.my.id/).

workflowSchedule:
graphs: "0 */6 * * *"
responseTime: "10 */6 * * *"
staticSite: "20 */6 * * *"
summary: "30 */6 * * *"
updateTemplate: "0 0 * * *"
updates: "40 */6 * * *"
uptime: "*/5 * * * *"
